server:
  port: 8082
spring:
  application:
    name: three-innovation
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://43.138.88.123:3306/three?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/three?useSSL=false&serverTimezone=UTC
#    username: three
    username: root
    password: abc123
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.three.domain # 别名扫描包
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.three: debug